apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jz7by3290-java-quarkus
  janus-idp.io/tekton: jz7by3290-java-quarkus
  backstage.io/kubernetes-id: jz7by3290-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jz7by3290-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
